<?php

function oj_init()
{
	$path = drupal_get_path('module','oj').'/misc/';
	drupal_add_css($path.'css/oj.css');
	drupal_add_css($path.'css/contactable.css');
	
	drupal_add_js($path.'jquery-ui/js/jquery-ui-1.7.3.custom.min.js');
	drupal_add_js($path.'js/oj.js');
	
	$js ='$(function(){$("#logout").click(function(){window.location="'.url('logout').'";});});';
	drupal_add_js($js,'inline');
}

function oj_menu()
{
	$items['admin/settings/oj'] = array
	(
		'title' => 'Online Judge',
		'description' => 'Configure settings for Online Judge.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('oj_settings'),
		'access arguments' => array('administer site configuration'),
	);
	
	$items['faq'] = array
	(
		'title' => 'Frequently Asked Questions',
		'page callback' => 'oj_faq',
		'access callback' => TRUE,
		'type' => MENU_SUGGESTED_ITEM
	);
	
	$items['hook_exist'] = array
	(
		'title' => 'Hook Exist',
		'page callback' => 'hook_exist',
		'page arguments' => array(1),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK
	);
	
	$items['oj_submissions_statistics'] = array
	(
		'title' => 'Submissions Statistics',
		'page callback' => 'oj_submissions_statistics',
		'page arguments' => array(1),
		'access callback' => TRUE,
		//'type' => MENU_CALLBACK
	);
	
	$items['test'] = array
	(
		'title' => 'Test',
		'page callback' => 'oj_test',
		'page arguments' => array(1),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK
	);
	return $items;
}

function oj_perm()
{
	return array('oj_import_data');
}

function oj_theme()
{
	return array
	(
		'oj_faq' => array
		(
			'arguments' => array('path' => NULL),
			'template' => 'faq',
		)
	);
}

function oj_cron()
{
	if(function_exists('_oj_user_cron'))
	{
		_oj_user_cron();
	}
	if(function_exists('_oj_problem_cron'))
	{
		_oj_problem_cron();
	}
	if(function_exists('_oj_contest_cron'))
	{
		_oj_contest_cron();
	}
	if(function_exists('_oj_solution_cron'))
	{
		_oj_solution_cron();
	}
}

function oj_settings()
{
	$form['oj_import_user'] = array
	(
		'#type' => 'fieldset',
		'#title' => 'User Import',
		'#collapsible' => TRUE,
	);
	$form['oj_import_user']['last_uid'] = array
	(
		'#type' => 'textfield',
		'#title' => t('Last imported user number'),
		'#default_value' => variable_get('last_import_user',0),
		'#size' => 10,
	);
	$form['oj_import_user']['user_num'] = array
	(
		'#type' => 'select',
		'#title' => t('Import number per time'),
		'#default_value' => variable_get('import_user_num',50),
		'#options' => drupal_map_assoc(array(10,20,50,100)),
	);
	
	$form['oj_import_problem'] = array
	(
		'#type' => 'fieldset',
		'#title' => 'Problem Import',
		'#collapsible' => TRUE,
	);
	$form['oj_import_problem']['last_pid'] = array
	(
		'#type' => 'textfield',
		'#title' => t('Last imported problem number'),
		'#default_value' => variable_get('last_import_problem',1000),
		'#size' => 10,
	);
	$form['oj_import_problem']['problem_num'] = array
	(
		'#type' => 'select',
		'#title' => t('Import number per time'),
		'#default_value' => variable_get('import_problem_num',20),
		'#options' => drupal_map_assoc(array(10,20,30,50)),
	);
	
	$form['oj_import_contest'] = array
	(
		'#type' => 'fieldset',
		'#title' => 'Contest Import',
		'#collapsible' => TRUE,
	);
	$form['oj_import_contest']['last_cid'] = array
	(
		'#type' => 'textfield',
		'#title' => t('Last imported contest number'),
		'#default_value' => variable_get('last_import_contest',1000),
		'#size' => 10,
	);
	$form['oj_import_contest']['contest_num'] = array
	(
		'#type' => 'select',
		'#title' => t('Import number per time'),
		'#default_value' => variable_get('import_contest_num',10),
		'#options' => drupal_map_assoc(array(5,10,20,30,50)),
	);
	
	$form['oj_import_solution'] = array
	(
		'#type' => 'fieldset',
		'#title' => 'Solution Import',
		'#collapsible' => TRUE,
	);
	$form['oj_import_solution']['last_sid'] = array
	(
		'#type' => 'textfield',
		'#title' => t('Last imported solution number'),
		'#default_value' => variable_get('last_import_solution',1000),
		'#size' => 10,
	);
	$form['oj_import_solution']['solution_num'] = array
	(
		'#type' => 'select',
		'#title' => t('Import number per time'),
		'#default_value' => variable_get('import_solution_num',100),
		'#options' => drupal_map_assoc(array(20,50,100,200,500)),
	);
	
	$form['#validate'][] = 'oj_settings_validate';
	$form['#submit'][] = 'oj_settings_submit';
	return system_settings_form($form);
}

function oj_settings_validate($form,$form_state)
{
	if(!is_numeric($form_state['values']['last_uid']) || $form_state['values']['last_uid']<0)
		form_set_error('last_uid','The last imported user number is incorrect.');
	
	if(!is_numeric($form_state['values']['last_pid']) || $form_state['values']['last_pid']<1000)
		form_set_error('last_pid','The last imported problem number is incorrect.');
	
	if(!is_numeric($form_state['values']['last_cid']) || $form_state['values']['last_cid']<1000)
		form_set_error('last_cid','The last imported contest number is incorrect.');
	
	if(!is_numeric($form_state['values']['last_sid']) || $form_state['values']['last_sid']<1000)
		form_set_error('last_sid','The last imported solution number is incorrect.');
}

function oj_settings_submit($form,$form_state)
{
	variable_set('last_import_user',$form_state['values']['last_uid']);
	variable_set('import_user_num',$form_state['values']['user_num']);
	
	variable_set('last_import_problem',$form_state['values']['last_pid']);
	variable_set('import_problem_num',$form_state['values']['problem_num']);
	
	variable_set('last_import_contest',$form_state['values']['last_cid']);
	variable_set('import_contest_num',$form_state['values']['contest_num']);
	
	variable_set('last_import_solution',$form_state['values']['last_sid']);
	variable_set('import_solution_num',$form_state['values']['solution_num']);
}

function oj_login_form($form_state)
{
	$form = array
	(
		'#action' => url($_GET['q'], array('query' => drupal_get_destination())),
		'#id' => 'oj-login-form',
	);
    $form['name'] = array
    (
		'#type' => 'textfield',
		'#title' => t('Username'),
		'#maxlength' => USERNAME_MAX_LENGTH,
		'#size' => 15,
		'#required' => TRUE,
    );
	$form['pass'] = array
	(
		'#type' => 'password',
		'#title' => t('Password'),
		'#maxlength' => 60,
		'#size' => 15,
		'#required' => TRUE,
	);
	$form['submit'] = array
	(
		'#type' => 'submit',
		'#value' => t('Log in'),
		'#validate' => user_login_default_validators(),
		'#submit' => array('oj_login_submit','user_login_submit'),
	);
	$form['register'] = array
	(
		'#value' => '<a href=user/register>Register</a>',
	);
	
	return $form;
}

function oj_faq()
{
	$path = drupal_get_path('module','oj');
	//return theme('oj_faq',$path);
	$html = <<<SCR
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="/drupal/misc/favicon.ico" type="image/x-icon" />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
<title>OnlineJudge F.A.Q</title>
<link type="text/css" rel="stylesheet" href="{$path}/misc/css/faq.css" />
<link type='text/css' rel='stylesheet' href='{$path}/misc/js/dp.SyntaxHighlighter/Styles/shCore.css'/>
<link type='text/css' rel='stylesheet' href='{$path}/misc/js/dp.SyntaxHighlighter/Styles/shThemeDefault.css'/>
<script src='{$path}/misc/js/dp.SyntaxHighlighter/Scripts/shCore.js' type='text/javascript'></script>
<script src='{$path}/misc/js/dp.SyntaxHighlighter/Scripts/shBrushCpp.js' type='text/javascript'></script>
<script src='{$path}/misc/js/dp.SyntaxHighlighter/Scripts/shBrushJava.js' type='text/javascript'></script>
<script src='{$path}/misc/js/dp.SyntaxHighlighter/Scripts/shBrushDelphi.js' type='text/javascript'></script>
<script src='{$path}/misc/js/dp.SyntaxHighlighter/Scripts/shBrushPerl.js' type='text/javascript'></script>
<script src='{$path}/misc/js/dp.SyntaxHighlighter/Scripts/shBrushPhp.js' type='text/javascript'></script>
</head>

<body>
<div align="center" class="page">
<div class="bg">
 <div class="box">
<div class="faq">
<div class="faq_title">
<img width="32px" height="32px" src="{$path}/misc/images/search.gif" />
<b> Frequently Asked Questions</b>
</div>

<div class="faq_content"><br /><br />
<a name=io></a>
<div class="faq_content_Q">
<font color="#FF8040"><b>Q</b></font>：我的程序要在哪里输入和输出数据？
</div>
<font color="green"><b>A</b></font>：你的程序必须从stdin（基本输入）读入数据并且从stdout（基本输出）输出数据。 <br />
例如，你使用C语言的话，使用scanf输入数据，使用printf输出数据，使用C++语言的话，还可以使用cin和cout读入输出数据。<br />
读写创建文件及调用其它程序等操作将会被系统忽略。<br /><br /huoz>

<a name=gcc></a>
<hr />
<div class="faq_content_Q">
<font color="#FF8040"><b>Q</b></font>：本OnlineJudge提供哪些编译器？编译环境是怎么样的？
</div>
<font color="green"><b>A</b></font>：本OJ目前提供GNU C/C++、Free Pascal、Java等编译器，它们的编译参数是：<br />
G++:<font color=blue>g++.exe -fno-asm -s -w -O1 -DONLINE_JUDGE -o %PATH%%NAME% %PATH%%NAME%.%EXT%</font><br />
GCC:<font color=blue>gcc.exe -fno-asm -s -w -O1 -DONLINE_JUDGE -o %PATH%%NAME% %PATH%%NAME%.%EXT%</font><br />
Pascal:<font color=blue>fpc.exe -Sg -dONLINE_JUDGE %PATH%%NAME%.%EXT%</font><br />
Java:<font color=blue>Java.bat %PATH%</font><br />
Masm32:<font color=blue>masm32.bat %PATH% %NAME% %EXT%</font><br />
<br />
我们的服务器运行在Windows NT平台下，提供的编译器的版本分别是：<br>
<li>Gcc/G++ Version 3.4.2 (mingw special)</li>
<li>FFree Pascal Compiler version 1.0.10 [2003/06/27] for i386</li>
<li>Java SDK Version 1.6.0_22</li><br /><br />

<a name=ce></a>
<hr />
<div class="faq_content_Q">
<font color="#FF8040"><b>Q</b></font>：为什么我得到了CE？而在我的电脑上运行的很好？
</div>
<font color="green"><b>A</b></font>：不同的编译器之间有一些语法的差异，请使用相应的编译器进行提交。<br />
另外，我们的OJ对编译器所使用的资源有所限制，限制是：CPU时间5秒，内存使用128MB，如果你使用的编译器在编译你的程序时超过这个资源限制，将被判为CE。<br />
当你使用G++、GCC时main()函数返回值必须是int，否则你可能会得到CE。<br /><br />

<a name=sj></a>
<hr />
<div class="faq_content_Q">
<font color="#FF8040"><b>Q</b></font>：有些题目上面有“Special Judge”是什么意思？
</div>
<font color="green"><b>A</b></font>：Special Judge是指本题可能有多个正确的解。你的程序的答案将被一个SPJ的检测程序检测，以判断你的程序是否正确。</br>
请注意：SPJ的题目一般不会判出PE，所以请确保你的程序输出格式正确。<br /><br />

<a name=int64></a>
<hr />
<div class="faq_content_Q">
<font color="#FF8040"><b>Q</b></font>：我要怎么使用64-bit整形？
</div>
<font color="green"><b>A</b></font>：在C/C++和Pascal语言中，你可以用以下方法使用64-bit整形：
<ul>
<li>
有符号64-bit整形，取值范围为：-9223372036854775808 到 9223372036854775807。
	<center><table border=1 style="width:650px;">
	<tr align=center>
		<td>语言</td>
		<td>GCC/G++</td>
		<td>Pascal</td>
		<td>VC/VC++</td>
	</tr>
	<tr align=center>
		<td>类型名称</td>
		<td>long long</td>
		<td>int64</td>
		<td>__int64<br />long long</td>
	</tr>
	<tr align=center>
		<td>输入方法</td>
		<td>scanf("%I64d", &amp;x);<br />cin >> x;</td>
		<td>read(x);</td>
		<td>scanf("%I64d", &amp;x);<br />cin >> x;</td>
	</tr>
	<tr align=center>
		<td>输出方法</td>
		<td>printf("%I64d", x);<br />cout &lt;&lt; x;</td>
		<td>write(x);</td>
		<td>printf("%I64d", x);<br />cout &lt;&lt; x;</td>
	</tr>
	</table></center>
</li>
<li>
无符号64-bit整形，取值范围为：0 到 18446744073709551615。
	<center><table border=1 style="width:650px;">
	<tr align=center>
		<td>语言</td>
		<td>GCC/G++</td>
		<td>Pascal</td>
		<td>VC/VC++</td>
	</tr>
	<tr align=center>
		<td>类型名称</td>
		<td>unsigned long long</td>
		<td>qword</td>
		<td>unsigned __int64<br />unsigned long long</td>
	</tr>
	<tr align=center>
		<td>输入方法</td>
		<td>scanf("%I64u", &x);<br />cin >> x;</td>
		<td>read(x);</td>
		<td>scanf("%I64u", &x);<br />cin >> x;</td>
	</tr>
	<tr align=center>
		<td>输出方法</td>
		<td>printf("%I64u", x);<br />cout &lt;&lt; x;</td>
		<td>write(x);</td>
		<td>printf("%I64u", x);<br />cout &lt;&lt; x;</td>
	</tr>
	</table></center>
</li>
</ul>
<br />

<a name=r></a>
<hr />
<div class="faq_content_Q">
<font color="#FF8040"><b>Q</b></font>：OJ返回的结果分别是什么意思？
</div>
<font color="green"><b>A</b></font>：以下是OJ可能返回的结果和其意义：<br />
<br />
<center>
<table border=1 style="width:800px;">
<tr><td width="17%"><font color=red>Accepted</font></td><td style="text-align:left">OK! 你的程序是正确的。</td></tr>
<tr><td><font color=#ff03fa>Presentation Error</font></td><td style="text-align:left">你的输出结果是正确的，但格式不正确，可能是你多输出或少输出了空格、Tab(\t)、换行(\n)等，请检查你的程序输出。</td></tr>
<tr><td><font color=1aae00>Wrong Answer</font></td><td style="text-align:left">你的程序输出的结果不正确。</td></tr>
<tr><td><font color=#ff9900>Time Limit Exceed</font></td><td style="text-align:left">你的程序尝试使用超过题目限制的时间，可能是你的程序内存在死循环或者你的程序的算法效率太低。</td></tr>
<tr><td><font color=#0692ff>Memory Limit Exceed</font></td><td style="text-align:left">你的程序尝试使用超过题目限制的内存。</td></tr>

<tr><td><font color=#bb338f>Runtime Error</font></td><td style="text-align:left">你的程序发生了运行时错误。可能是由于除于0、内存访问违规等运行时问题。</td></tr>
<tr><td><font color=#1e9e00>Compile Error</font></td><td style="text-align:left">你的程序不能通过编译，请点击该结果可以查看编译器提示。</td></tr>
<tr><td><font color=#999999>Output Limit Exceed</font></td><td style="text-align:left">你的程序的输出超过了系统限制。请检查你的程序是否存在死循环问题。目前系统的限制是8MB。</td></tr>
<tr>
  <td><font color=#ff3030><b>Waiting</b></font></td>
  <td style="text-align:left">你的程序正在评测当中，请稍候。</td></tr>
<tr><td><font color=balck>Data Error</font></td><td style="text-align:left">测试数据文件错误，请告知管理员。</td></tr>
<tr><td><font color=black>System Error</font></td>
<td style="text-align:left">未知错误，如果有该评测结果，请及时联系管理员。</td>
</tr>
</table>
</center>
注意：对于Java语言，有极少部分可能将RFC与RE判成WA。<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Perl、PHP脚本语言暂时无法判断CE。<br />

<a name=key></a>
<hr />
<div class="faq_content_Q">
<font color="#FF8040"><b>Q</b></font>：我提交代码时能使用快捷键吗？
</div>
<font color="green"><b>A</b></font>：
下面是提交页面的快捷键:
</br>
ALT+S    :提交
</br>
ALT+U    :用户名（未登陆时）
</br>
ALT+L    :语言选项
</br>
ALT+P    :问题编号
<br /><br />
<hr />

<a name=1000></a>
<div class="faq_content_Q">
<font color="#FF8040"><b>Q</b></font>：1000题怎么解答？
</div>
<font color="green"><b>A</b></font>：以下是1000题的各种语言的参考程序：<br />
C++语言:<br />
<pre class='brush: cpp;toolbar: false;'>
#include &lt;iostream&gt;
using namespace std;
int main()
{
  int a,b;
  while(cin&gt;&gt;a&gt;&gt;b) 
	cout&lt;&lt;a+b&lt;&lt;endl;
  return 0;
}
</pre>

C语言：<br />
<pre class='brush: c;toolbar: false;'>
#include &lt;stdio.h&gt;
int main()
{
  int a,b;
  while(scanf("%d%d",&a,&b)!=EOF) 
    printf("%d\\n",a+b);
  return 0;
}
</pre>

PASCAL语言：
<pre class='brush: pascal;toolbar: false;'>
var
  a,b:integer;
begin
  while not eof do begin
    readln(a,b);
    writeln(a+b);
  end;
end.
</pre>

Java语言：
<pre class='brush: java;toolbar: false;'>
import java.io.*;
import java.util.*;
public class Main
{
	public static void main(String[] args)
	{
		Scanner cin = new Scanner(new BufferedInputStream(System.in));
		int a,b;
		while(cin.hasNext())
		{
			a = cin.nextInt();
			b = cin.nextInt();
			System.out.println(a+b);
		}

	}
}
</pre>

Perl语言：
<pre class='brush: perl;toolbar: false;'>
my @a;
while(<>)
{
    @a = split(' ',\$_);
    \$a[0] += \$a[1];
    print "\$a[0]\\n";
}
</pre>

PHP语言：
<pre class='brush: php;toolbar: false;'>
&lt;?php
\$stdin = fopen('php ://stdin', 'r');
while (fscanf(\$stdin, "%d%d", \$a, \$b) == 2)
    print (\$a + \$b) . "\\n";
</pre>
<script type="text/javascript">SyntaxHighlighter.all();</script>

<br />
</div>
</div>
</div>
</div><!-- bg -->

</div><!-- center -->

</body>
</html>

SCR;
	print phpcharset($html,'UTF-8');
}

function oj_check_markup($text, $format = FILTER_FORMAT_DEFAULT, $check = FALSE)
{
	
	// When $check = TRUE, do an access check on $format.
	if (isset($text) && (!$check || filter_access($format)))
	{
		$format = filter_resolve_format($format);

		// Check for a cached version of this piece of text.
		$cache_id = $format . ':' . md5($text);
		if ($cached = cache_get($cache_id, 'cache_filter'))
		{
			return $cached->data;
		}

		// See if caching is allowed for this format.
		$cache = filter_format_allowcache($format);

		// Convert all Windows and Mac newlines to a single newline,
		// so filters only need to deal with one possibility.
		$text = str_replace(array("\r\n", "\r"), "\n", $text);

		// Get a complete list of filters, ordered properly.
		$filters = filter_list_format($format);

		// Give filters the chance to escape HTML-like data such as code or formulas.
		foreach ($filters as $filter)
		{
			$text = module_invoke($filter->module, 'filter', 'prepare', $filter->delta, $format, $text, $cache_id);
		}

		// Perform filtering.
		foreach ($filters as $filter)
		{
			$text = module_invoke($filter->module, 'filter', 'process', $filter->delta, $format, $text, $cache_id);
		}

		// Store in cache with a minimum expiration time of 1 day.
		if ($cache)
		{
			cache_set($cache_id, $text, 'cache_filter', time() + (60 * 60 * 24));
		}
	}
	//$text = str_replace("\n", "<br>", $text);
	return $text;
}

function oj_get_value($key)
{
	$file = variable_get('oj_config_file',"C:\JudgeOnline\server.config");
	$var = parse_ini_file($file);
	return $var[$key];
}

function oj_languages($type = FALSE)
{
	$language = explode(',',oj_get_value('LanguageDescs'));
	if($type)
		return $language;
	foreach($language as $value)
	{
		$languages[$value] = $value;
	}
	return $languages;
}

function oj_judge_value($key,$id)
{
	$value = explode(',',oj_get_value($key));
	return $value[$id];
}

function oj_get_status_result($flag = FALSE)
{
	$status_result = array
	(
		0 => "AC",
		1 => "PE",
		2 => "TLE",
		3 => "MLE",
		4 => "WA",
		5 => "RE",
		6 => "OLE",
		7 => "CE",
		98 => "System Error",
		99 => "Validate Error",
		100 => "Data Error",
		10000 => "Waiting"
	);
	if($flag == TRUE)
	{
		foreach($status_result as $key => $value)
		{
			$descript[$key] = getResultDescript($key);
		}
		return $descript;
	}
	return $status_result;
}

function oj_get_status_color($num = NULL)
{
	$colors = array
	(
		0 => '#ff0000',
		1 => '#ff03fa',
		2 => '#ff9900',
		3 => '#0692ff',
		4 => '#000000',
		5 => '#bb338f',
		6 => '#999999',
		7 => '#1e9e00',
		98 => '#579575',
		99 => '#839557',
		100 => '#958c12',
		10000 => '#00ff00',
	);
	return $colors;
}

function getResultDescript($i)
{
	if ($i == 0)
		return "<font color=red><b>Accepted</b></font>";
	if ($i == 1)
		return "<font color=#ff03fa>Presentation Error</font>";
	if ($i == 2)
		return "<font color=#ff9900>Time Limit Exceed</font>";
	if ($i == 3)
		return "<font color=#0692ff>Memory Limit Exceed</font>";
	if ($i == 4)
		return "<font color=#000000>Wrong Answer</font>";
	if ($i == 5)
		return "<font color=#bb338f>Runtime Error</font>";
	if ($i == 6)
		return "<font color=#999999>Output Limit Exceed</font>";
	if ($i == 7)
		return "<font color=#1e9e00>Compile Error</font>";
	if ($i == 10000)
		return "<font color=green>Waiting</font>";
	if ($i == 98)
		return "<font color=black>System Error</font>";
	if ($i == 99)
		return "Validate Error";
	if ($i == 100)
		return "Data Error";
	return "Other";
}

function deldir($dir)
{
	//先删除目录下的文件：
	$dh = opendir($dir);
	while ($file = readdir($dh))
	{
		if($file != '.' && $file != '..')
		{
			$fullpath = $dir.'/'.$file;
			if(!is_dir($fullpath))
				unlink($fullpath);
			else
				deldir($fullpath);
		}
	}
	closedir($dh);
	//删除当前文件夹：
	if(rmdir($dir))
		return true;
	else
		return false;
}

/*
* date format like 2012-02-13 21:58:49
*/
function oj_date($time = NULL)
{
	if($time == NULL)
		$time = time();
	return format_date($time,'custom','Y-m-d H:i:s');
}

function hook_exist($type = NULL)
{
	//print "<pre>\n";
	if($type == NULL)
	{
		
	}
	foreach (module_implements($type) as $module)
	{
		$function = $module . '_' . $type;
		print $function."\n";
	}
	/*foreach (module_implements($type . '_alter') as $module)
	{
		$function = $module . '_' . $type . '_alter';
		print $function."\n";
	}*/
	//print "</pre>\n";
}

function oj_test($par=NULL)
{
	$str = file('http://localhost/drupal/code/33239');
	foreach($str as $line)
		$output .= $line;
	/*// 创建一个新cURL资源
	$ch = curl_init();

	// 设置URL和相应的选项
	curl_setopt($ch,CURLOPT_URL, "http://localhost/drupal/code/33239");
	curl_setopt($ch,CURLOPT_HEADER, false);
	curl_setopt($ch,CURLOPT_POST,1);
	curl_setopt($ch,CURLOPT_POSTFIELDS,'op=check');
	// 抓取URL并把它传递给浏览器
	$str = curl_exec($ch);
	
	
	//关闭cURL资源，并且释放系统资源
	curl_close($ch);
*/
$js =<<<JS
			<script type="text/javascript">
			//alert($('#check_code').val());
				$('.functions').each(function(i)
				{
					alert($(this).val());
					$('#check_code').append($(this).val());
				});
			</script>
JS;
	//drupal_add_js($js,'inline');
	//debug($output);
	echo $output.$js;
	//return "<pre>".check_plain($output)."</pre>";
}

function microtime_float()
{
    list($usec, $sec) = explode(" ", microtime());
    return ($usec + $sec) * 1000;
}

function is_admin_login()
{
	global $user;
	if($user->uid == 1)
		return true;
	if($user->roles['5'] != NULL)
		return true;
	return false;
}

function is_root_login()
{
	global $user;
	return $user->uid == 1;
}

// debug function to dump an array into a temp file
function debug($var,$title = NULL,$filename = NULL)
{
	if($filename == NULL)
		$filename = 'debug.txt';
	$f = fopen($filename,'a');
	ob_start();
	print("===== $title(".gettype($var).") =====\r\n");
	$call = debug_backtrace();
	print $call[0]['file'].',line '.$call[0]['line']."\r\n\r\n";
	//print "File: ". __FILE__ ." Line: ". __LINE__ ."\r\n\r\n";
	print_r($var);
	print("\n\n");
	fwrite($f,ob_get_contents());
	ob_end_clean();
	fclose($f);
}

/*
* Convert charset
*/
function phpcharset($data, $to)
{
	$encode_array = array('ASCII', 'UTF-8', 'GBK', 'GB2312', 'BIG5');
	$encoded = mb_detect_encoding($data, $encode_array);
	$data = mb_convert_encoding($data, $to, $encoded);
	return $data;
}


/**
 * Does the very standard things that must be done in any normal callback.
 * Used by each callback in this example module.
 */
function ahah_callback_helper() {
  $form_state = array('storage' => NULL, 'submitted' => FALSE);
  $form_build_id = $_POST['form_build_id'];
  $form = form_get_cache($form_build_id, $form_state);
  $args = $form['#parameters'];
  $form_id = array_shift($args);
  $form_state['post'] = $form['#post'] = $_POST;
  // Enable the submit/validate handlers to determine whether AHAH-submittted.
  $form_state['ahah_submission'] = TRUE;
  $form['#programmed'] = $form['#redirect'] = FALSE;
  drupal_process_form($form_id, $form, $form_state);
  $form = drupal_rebuild_form($form_id, $form_state, $args, $form_build_id);
  return $form;
}

function oj_submissions_statistics($days)
{
	$width = 800;
	if($days<1)
		$days = 7;
	if($days>30)
		$days = 30;
	if($days>20)
		$width = 1200;
	return _oj_submissions_statistics($days,$width);
}

function _oj_submissions_statistics($days = 7,$width = 800)
{
	date_default_timezone_set("Asia/Chongqing");
	$title = new title("Daily Submissions(".date("D M d Y H:i:s").")");
	$title->set_style('{color: #567300; font-size: 14px}');
	
	$max_y = 0;
	$data = array();
	
	for($i=$days-1;$i>=0;$i--)
	{
		$item = db_fetch_object(db_query("SELECT COUNT(*) AS num,DATE_SUB(CURDATE(),INTERVAL %d DAY) AS date FROM solution WHERE FROM_UNIXTIME(in_date,'%Y-%m-%%d') = DATE_SUB(CURDATE(),INTERVAL %d DAY)",$i,$i));
        $data[] = (int)$item->num;
		$x_label[] = substr($item->date,5);
		$max_y = max($max_y,$item->num);
	}
	
	$d = new solid_dot();
	$d->size(3)->halo_size(1)->colour('#ff0000');

	$line = new line();
	$line->set_default_dot_style($d);
	$line->set_values($data);
	$line->set_width(2);
	$line->set_colour('#3D5C56');

	$chart = new open_flash_chart();
	$chart->set_title($title);
	$chart->add_element($line);
	
	$max_y_t = (int)round($max_y/10)*10;
	$max_y += $max_y_t/10;
	$y = new y_axis();
	$y->set_range(0,$max_y,(int)round($max_y/10));
	
	$x = new x_axis();
	$x->set_labels_from_array($x_label);
	$chart->set_x_axis($x);
	$chart->add_y_axis($y);
	
	return "<div class=open_flash_chart>".ofc_api_render($chart,$width)."</div>";
}
